###
GET http://localhost:7070/client-trade-details/all-clients

###
GET http://localhost:7070/client-trade-details/by-product-grouping/stocks

###
GET http://localhost:7070/client-trade-details/by-revenue-range?minRevenue=3000000&maxRevenue=4000000

###
GET http://localhost:7070/client-trade-details/by-time-of-execution?startDate=2023-01-10&endDate=2023-04-30

###
GET http://localhost:7070/client-trade-details/by-date-and-clientId?clientId=542&startDate=2023-01-10&endDate=2023-08-30

###
GET http://localhost:7070/client-trade-details/clients/542/trades/bonds

###
GET http://localhost:7070/client-trade-details/trades/by-date/Stocks?startDate=2023-01-01&endDate=2023-12-31

###
GET http://localhost:7070/client-trade-details/trades/by-revenue/Stocks?minRevenue=1000000&maxRevenue=2000000

###
GET http://localhost:7070/client-trade-details/trades/by-date-and-clientId?clientId=555&startDate=2023-01-01&endDate=2023-12-31